# Generated by Django 3.1 on 2021-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scanned_times',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
