# Generated by Django 3.1 on 2021-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210531_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scanned_times',
            field=models.CharField(choices=[('Second', 'Second'), ('First', 'First'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
