# Generated by Django 3.1 on 2021-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210531_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scanned_times',
            field=models.CharField(choices=[('First', 'First'), ('None', 'None'), ('Second', 'Second')], default='None', max_length=10),
        ),
    ]
