# Generated by Django 3.1 on 2021-05-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default='', max_length=255, unique=True)),
                ('image_obj', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanpage.qrcode')),
            ],
        ),
    ]
